export const getTransactionsByUser = (userId: string) => {
  // Simulação de dados para transações financeiras
  return [
    {
      id: '1',
      amount: 1500,
      type: 'income',
      description: 'Pagamento de honorários - Processo A',
      category: 'fees',
      date: new Date(2023, 4, 15),
      status: 'completed',
      clientId: 'c1',
      clientName: 'Cliente A',
      processId: 'p1',
      processName: 'Processo A',
      paymentMethod: 'transfer',
      reference: 'REF001',
      currency: 'BRL',
      notes: 'Pagamento integral',
      createdBy: 'admin',
      createdAt: new Date(2023, 4, 10),
      updatedAt: new Date(2023, 4, 15),
      dueDate: new Date(2023, 4, 20),
      attachments: [],
    },
    {
      id: '2',
      amount: 800,
      type: 'income',
      description: 'Pagamento de honorários - Processo B',
      category: 'fees',
      date: new Date(2023, 4, 20),
      status: 'pending',
      clientId: 'c2',
      clientName: 'Cliente B',
      processId: 'p2',
      processName: 'Processo B',
      paymentMethod: 'boleto',
      reference: 'REF002',
      currency: 'BRL',
      notes: '',
      createdBy: 'admin',
      createdAt: new Date(2023, 4, 18),
      updatedAt: new Date(2023, 4, 20),
      dueDate: new Date(2023, 4, 25),
      attachments: [],
    },
    {
      id: '3',
      amount: 250,
      type: 'expense',
      description: 'Custas judiciais',
      category: 'court_fees',
      date: new Date(2023, 4, 22),
      status: 'completed',
      clientId: 'c1',
      clientName: 'Cliente A',
      processId: 'p1',
      processName: 'Processo A',
      paymentMethod: 'cartao',
      reference: 'REF003',
      currency: 'BRL',
      notes: 'Despesa processual',
      createdBy: 'admin',
      createdAt: new Date(2023, 4, 21),
      updatedAt: new Date(2023, 4, 22),
      dueDate: new Date(2023, 4, 30),
      attachments: [],
    },
    {
      id: '4',
      amount: 120,
      type: 'expense',
      description: 'Material de escritório',
      category: 'supplies',
      date: new Date(2023, 4, 25),
      status: 'completed',
      clientId: null,
      clientName: null,
      processId: null,
      processName: null,
      paymentMethod: 'dinheiro',
      reference: 'REF004',
      currency: 'BRL',
      notes: '',
      createdBy: 'admin',
      createdAt: new Date(2023, 4, 24),
      updatedAt: new Date(2023, 4, 25),
      dueDate: null,
      attachments: [],
    }
  ];
};
