
export enum UserRole {
  ADMIN = 'admin',
  LAWYER = 'lawyer',
  SENIOR_LAWYER = 'senior_lawyer',
  ASSISTANT = 'assistant',
  CLIENT = 'client'
}

export type Permission =
  | 'CLIENTS_CREATE'
  | 'CLIENTS_READ'
  | 'CLIENTS_UPDATE'
  | 'CLIENTS_DELETE'
  | 'PROCESSES_CREATE'
  | 'PROCESSES_READ'
  | 'PROCESSES_UPDATE'
  | 'PROCESSES_DELETE'
  | 'DOCUMENTS_CREATE'
  | 'DOCUMENTS_READ'
  | 'DOCUMENTS_UPDATE'
  | 'DOCUMENTS_DELETE'
  | 'CALENDAR_CREATE'
  | 'CALENDAR_READ'
  | 'CALENDAR_UPDATE'
  | 'CALENDAR_DELETE'
  | 'BILLING_CREATE'
  | 'BILLING_READ'
  | 'BILLING_UPDATE'
  | 'BILLING_DELETE'
  | 'USERS_CREATE'
  | 'USERS_READ'
  | 'USERS_UPDATE'
  | 'USERS_DELETE';

export const DEFAULT_ROLE_PERMISSIONS: Record<UserRole, Permission[]> = {
  [UserRole.ADMIN]: [
    'CLIENTS_CREATE', 'CLIENTS_READ', 'CLIENTS_UPDATE', 'CLIENTS_DELETE',
    'PROCESSES_CREATE', 'PROCESSES_READ', 'PROCESSES_UPDATE', 'PROCESSES_DELETE',
    'DOCUMENTS_CREATE', 'DOCUMENTS_READ', 'DOCUMENTS_UPDATE', 'DOCUMENTS_DELETE',
    'CALENDAR_CREATE', 'CALENDAR_READ', 'CALENDAR_UPDATE', 'CALENDAR_DELETE',
    'BILLING_CREATE', 'BILLING_READ', 'BILLING_UPDATE', 'BILLING_DELETE',
    'USERS_CREATE', 'USERS_READ', 'USERS_UPDATE', 'USERS_DELETE'
  ],
  [UserRole.SENIOR_LAWYER]: [
    'CLIENTS_CREATE', 'CLIENTS_READ', 'CLIENTS_UPDATE',
    'PROCESSES_CREATE', 'PROCESSES_READ', 'PROCESSES_UPDATE',
    'DOCUMENTS_CREATE', 'DOCUMENTS_READ', 'DOCUMENTS_UPDATE',
    'CALENDAR_CREATE', 'CALENDAR_READ', 'CALENDAR_UPDATE',
    'BILLING_READ', 'BILLING_UPDATE',
    'USERS_READ'
  ],
  [UserRole.LAWYER]: [
    'CLIENTS_READ',
    'PROCESSES_CREATE', 'PROCESSES_READ', 'PROCESSES_UPDATE',
    'DOCUMENTS_CREATE', 'DOCUMENTS_READ', 'DOCUMENTS_UPDATE',
    'CALENDAR_CREATE', 'CALENDAR_READ', 'CALENDAR_UPDATE',
    'BILLING_READ'
  ],
  [UserRole.ASSISTANT]: [
    'CLIENTS_READ',
    'PROCESSES_READ',
    'DOCUMENTS_CREATE', 'DOCUMENTS_READ',
    'CALENDAR_READ'
  ],
  [UserRole.CLIENT]: [
    'PROCESSES_READ',
    'DOCUMENTS_READ',
    'CALENDAR_READ',
    'BILLING_READ'
  ]
};
