import { formatDate } from "@/utils/dateUtils";
import { Document, DocumentTemplate } from "@/types/document";

// Mock documents data
export const mockDocuments: Document[] = [
  {
    id: "doc1",
    name: "Contrato de Prestação de Serviços",
    type: "document",
    size: "2.4 MB",
    updatedAt: formatDate(new Date(2023, 5, 15)),
    owner: "João Silva",
    folder: "Contratos",
    process: "Processo 2023/001",
    tags: ["contrato", "serviços", "cliente"],
    status: "final",
    description: "Contrato padrão de prestação de serviços jurídicos",
    category: "Contratos",
    clientId: "client1",
    processId: "process1",
    url: "/documents/doc1.pdf",
    version: 1,
  },
  {
    id: "doc2",
    name: "Petição Inicial",
    type: "action",
    size: "1.8 MB",
    updatedAt: formatDate(new Date(2023, 5, 20)),
    owner: "Maria Santos",
    folder: "Processos",
    process: "Processo 2023/002",
    tags: ["petição", "trabalhista"],
    status: "review",
    description: "Petição inicial para processo trabalhista",
    category: "Petições",
    clientId: "client2",
    processId: "process2",
    url: "/documents/doc2.pdf",
    version: 1,
  },
  {
    id: "doc3",
    name: "Jurisprudência STF",
    type: "precedent",
    size: "3.2 MB",
    updatedAt: formatDate(new Date(2023, 5, 10)),
    owner: "Carlos Mendes",
    folder: "Jurisprudência",
    process: "Processo 2023/003",
    tags: ["jurisprudência", "stf", "constitucional"],
    status: "archived",
    description: "Compilação de jurisprudência do STF sobre direito constitucional",
    category: "Jurisprudência",
    clientId: "client3",
    processId: "process3",
    url: "/documents/doc3.pdf",
    version: 1,
  },
  {
    id: "doc4",
    name: "Estratégia Processual",
    type: "strategy",
    size: "1.1 MB",
    updatedAt: formatDate(new Date(2023, 5, 25)),
    owner: "Ana Oliveira",
    folder: "Estratégias",
    process: "Processo 2023/004",
    tags: ["estratégia", "processo", "cliente"],
    status: "draft",
    description: "Documento de estratégia processual para caso de direito empresarial",
    category: "Estratégias",
    clientId: "client4",
    processId: "process4",
    url: "/documents/doc4.pdf",
    version: 1,
  },
  {
    id: "doc5",
    name: "Procuração",
    type: "document",
    size: "0.8 MB",
    updatedAt: formatDate(new Date(2023, 5, 18)),
    owner: "Pedro Costa",
    folder: "Documentos",
    process: "Processo 2023/005",
    tags: ["procuração", "cliente"],
    status: "signed",
    description: "Procuração com poderes específicos",
    category: "Documentos Pessoais",
    clientId: "client5",
    processId: "process5",
    url: "/documents/doc5.pdf",
    version: 1,
  },
];

// Mock templates data
export const mockTemplates: DocumentTemplate[] = [
  {
    id: "template1",
    name: "Contrato de Prestação de Serviços",
    description: "Modelo padrão de contrato de prestação de serviços jurídicos",
    category: "Contratos",
    tags: ["contrato", "serviços", "modelo"],
    type: "document",
    updatedAt: formatDate(new Date(2023, 4, 10)),
    size: "1MB"
  },
  {
    id: "template2",
    name: "Petição Inicial - Trabalhista",
    description: "Modelo de petição inicial para processos trabalhistas",
    category: "Petições",
    tags: ["petição", "trabalhista", "modelo"],
    type: "action",
    updatedAt: formatDate(new Date(2023, 4, 15)),
    size: "1MB"
  },
  {
    id: "template3",
    name: "Procuração Ad Judicia",
    description: "Modelo de procuração com poderes para representação judicial",
    category: "Documentos",
    tags: ["procuração", "modelo", "judicial"],
    type: "document",
    updatedAt: formatDate(new Date(2023, 4, 20)),
    size: "1MB"
  },
  {
    id: "template4",
    name: "Contestação - Cível",
    description: "Modelo de contestação para processos cíveis",
    category: "Petições",
    tags: ["contestação", "cível", "modelo"],
    type: "action",
    updatedAt: formatDate(new Date(2023, 4, 25)),
    size: "1MB"
  },
];

// Mock folders data
export const mockFolders = [
  { id: "folder1", name: "Contratos", count: 12 },
  { id: "folder2", name: "Processos", count: 8 },
  { id: "folder3", name: "Jurisprudência", count: 15 },
  { id: "folder4", name: "Estratégias", count: 5 },
  { id: "folder5", name: "Documentos", count: 20 },
];

// Mock tags data
export const mockTags = [
  { id: "tag1", name: "contrato", count: 8 },
  { id: "tag2", name: "petição", count: 6 },
  { id: "tag3", name: "jurisprudência", count: 12 },
  { id: "tag4", name: "estratégia", count: 4 },
  { id: "tag5", name: "cliente", count: 15 },
  { id: "tag6", name: "trabalhista", count: 7 },
  { id: "tag7", name: "cível", count: 9 },
  { id: "tag8", name: "constitucional", count: 5 },
];
